# Константы для настройки pdf-файла
TOP_MARGIN = 750
BOTTOM_MARGIN = 50
LEFT_MARGIN = 50
RIGHT_MARGIN = 550
LINE_HEIGHT = 20
DOUBLE_LINE_HEIGHT = 40
TITLE_FONT_SIZE = 16
FONT_SIZE = 12
RECIPE_TITLE_LIMIT = 64
PARAGRAPH_INDENTATION = 70
