# Generated by Django 6.0 on 2026-01-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_link',
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_link_token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
