# Generated by Django 6.0 on 2026-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_short_link_recipe_short_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link_token',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Токен короткой ссылки'),
        ),
    ]
