# Generated by Django 6.0 on 2026-01-20 12:25

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.models.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
